-- Create survey_results table
create table public.survey_results (
  id bigint generated by default as identity not null,
  app text not null,
  created_at timestamp with time zone not null default now(),
  answers json null,
  class text null,
  specialization text null,
  constraint survey_results_pkey primary key (id)
) TABLESPACE pg_default;